### ISSUE TITLE
Inquiry About Code Release Timeline

### ISSUE THREAD

**Issue by mikurules** [xinran-liu00/DAF-Net#1]
Hello,
I'd like to express my appreciation for the work you've done on DAF-Net. I recently came across your paper and was highly impressed by the innovative approaches and the results you've achieved.
I noticed that the README mentions "The code will be made public soon." As I'm keen on exploring your work in more depth, I was wondering if there might be an estimated timeline for when the code will be made available. Understanding your timeline can help me plan my research activities accordingly.
Thank you very much for your time and effort in advancing the field. Looking forward to the possibility of exploring your work in greater detail.

**Comment by xinran-liu00** [comment]
Hi the code has been released
